env:

 matrix:
   - WITH_AUTORECONF="yes" BUILD_COQ="yes"

before_script:
 - sudo apt-get update -q
 - ./etc/install_coq_deps.sh
 - ./etc/install_coq.sh -prefix /usr/local -debug

script:
 - coqc -nois -indices-matter bug_extensions_univ_helper_05.v
 - coqtop -nois -indices-matter -compile bug_extensions_univ_helper_05
 - coqtop -nois -indices-matter -load-vernac-source bug_extensions_univ_helper_05.v
 - coqc -nois -indices-matter tmp.v
 - coqtop -nois -indices-matter -compile tmp
 - coqtop -nois -indices-matter -load-vernac-source tmp.v
